name: deploy-infra
run-name: ${{ github.actor }} is ${{ github.workflow }}
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['infra/**', '**infra.yml']
jobs:
  deploy-cfn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1.3.0
        with:
          name: calling-agent
          template: infra/template.yml
          no-fail-on-empty-changeset: 1
          parameter-overrides: >-
            instanceType=${{ vars.INSTANCE_TYPE }},
            keyPairName=${{ vars.KEY_PAIR_NAME }},
            awsRegion=${{ vars.AWS_REGION }}